### ISSUE TITLE
Add support for LastPass Type 2 Account

### ISSUE THREAD

**Issue by mani9876** [Sappharad/Lastpass-SSO-DotNET#2]
Hello!

I need to run Lastpass within an C# Application, and I am trying to use https://github.com/detunized/password-manager-access I come across the issue, that 2FA / ADFS / SSO Logins are not working with the mentioned package.

I've tried your approach to open a WebView2 and gather the parameters, which than can be passed to the password-manager-access application.

But the problem is - we are using a Type 2 Account within LastPass, which points to a ADFS Authentication.

Have you got any information, on how it would be possible to get the credentials and pass them to the Lastpass API?

**Comment by Sappharad** [comment]
I don't have any additional information outside of what was provided in this repo.

Part of what helped me figure out the Azure AD SSO process was looking at jnewbigin's Okta implementation, then using browser dev tools to debug the LastPass browser extension during a login to see what data it was requesting and what it was doing with it. You may have luck trying to come up with your own implementation for other SSO providers by following the same process. Debug the official plugin in dev tools to see what traffic it sends and receives in the Network tab, if you're lucky it may just be a K1 and K2 value coming from somewhere that you just need to combine to come up with the SSO password.
